# Generated by Django 4.2.9 on 2024-03-08 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
